# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-02 03:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='numero_favorito',
            field=models.IntegerField(null=True),
        ),
    ]
